#!/bin/sh
JAVA_OPTS=""

if [ "${DEBUG}" = "true" ] ; then
	JAVA_OPTS="${JAVA_OPTS} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000"
fi

java ${JAVA_OPTS} -cp "/usr/lib/mux2fs/lib/*" se.tfiskgul.mux2fs.Main $@ &
